### ISSUE TITLE
Blacklist for fetch and xhr requests

### ISSUE THREAD

**Issue by rasjani** [alfonso-presa/testability-browser-bindings#1]
First a bit of background: I’ve been building a  plugin of sorts on top of Selenium for but over these now  that utilizes Testability js and these bindings and things work great.

For now I’ve opted out of actually modifying bindings but there has been a feature request towards my codebase that would better suite here.  

Scenario: SUT is not doing anything and it has ad code that tries to fetch something and due to random factors these ad calls can take long long time to either timeout or to just fail. URLs for these requests are known beforehand.  

Due to how fetch and xhr are mocked,there’s no way to avoid or ignore those. Would you consider a patch that would add a lookup table that is checked at runtime if the url in the arguments is in the lookup and if yes, counter wouldn’t be increased ?

**Comment by alfonso-presa** [comment]
Hi @rasjani,

That is something that indeed has a lot of sense. I was also evaluating adding a similar feature for long polling or stream services, which will aso block the test indefinitely. The problem I see is how to pass the whitelist to the bindings... The only way I can think of is by a global object, or by providing some `config` method in the testability object.... How were you planning to do it?

**Comment by rasjani** [comment]
My initial thought was that the testability.js would have the list and config setters/getters that the bindings can then use to if/when needed.  Simple global could also do, at least that would ease up configuration when testabilityjs and bindings are injected at runtime. At this time what i do when i instrument the sut is something like this:

```javascript
   window.testability = require('testability.js')
   window.instrumentBrowser = require('testability-browser-bindings')
   window.instrumentBrowser(window)
```

bindings import could take optional object that holds configuration and then "technical" details that needs to be agreed upon is essentially the structure (property names) of that object.

**Comment by alfonso-presa** [comment]
@rasjani, third option looks good. I guess it will be up to the test harness to provide a way for the users to configure the blacklist and other potential configuration options. I could try to find some time this weekend to implement the changes, but I can't promise.

**Comment by alfonso-presa** [comment]
@rasjani I'm sorry. I'm having very busy days lately :-(. I'll try to look for a slot this weekend... Anyway, if you were willing to PR for this it will be very welcome.

**Comment by rasjani** [comment]
np. One question:

adding ignorelist will be easier for xhr. Fetch uses this generating approach - which at the moment isnt used for anything else though - any particular way you would want this to be "future proofed" or ill come up with something and we'll discuss if there's any downsides of what i picked ?

**Comment by alfonso-presa** [comment]
@rasjani, to be honest I was simply thinking of checking if `fetch` parameter is a `Request` or string to gather the URL and checking the value against the whitelist.... Do you see any gaps in this approach?

About the capabilities of the white list (both Fetch and XMLHttpRequest), I was thinking of using URL with String and RegExp support and also the method optionally just in case.

**Comment by rasjani** [comment]
Patch referenced ^  -- i know for sure i need to refactor this to suite your code style and add the tests still  - but for now, any feedback ?

**Comment by alfonso-presa** [comment]
@rasjani This looks really good :-). I don't see too much refactor pending in current version. I would change the name of `patchPromiseFunction` to something like `patchFetch` as now it's not very agnostic from the patched functionality (but that's fair... it only had one single use).

Thank you!
